### ISSUE TITLE
Idea: mention `starry-night`, next to `/markdown` endpoint, for syntax highlighted code with this CSS

### ISSUE THREAD

**Issue by wooorm** [sindresorhus/github-markdown-css#101]
Hey!

I made https://github.com/wooorm/starry-night to solve the problem of highlighting code like GH but without needing API requests.

Given that syntax highlighting is explicitly mention in the readme, would you welcome a PR mentioning `starry-night`? (And if so, let me know if you have preferences on wording)

(I also ship just the GH CSS for syntax highlighting, generated using `generate-github-markdown-css`, thanks!)

**Comment by sindresorhus** [comment]
PR welcome. Wording up to you.
