### ISSUE TITLE
Support for Alerts

### ISSUE THREAD

**Issue by GigaArpit** [sindresorhus/github-markdown-css#108]
GitHub recently introduced Alerts. Please add support for these.

> [!TIP]
> Refer
> - https://github.blog/changelog/2023-12-14-new-markdown-extension-alerts-provide-distinctive-styling-for-significant-content/
> - https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by GigaArpit** [comment]
It looks like Alerts are not part of GitHub Flavored Markdown specs. 

>While GFM supports a wide range of inputs, it’s worth noting that GitHub.com and GitHub Enterprise perform additional post-processing and sanitization after GFM is converted to HTML to ensure security and consistency of the website. [source](https://github.github.com/gfm/#what-is-github-flavored-markdown-)

> They are implemented as a post processing step on a sort of "DOM" version of the resulting document. [source](https://github.com/github/cmark-gfm/issues/350#issuecomment-1747789268)

So, I'm closing this issue here. I still want this to be implemented. Thoughts @sindresorhus?

**Comment by jd-solanki** [comment]
@GigaArpit I guess it is: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts

**Comment by flying-sheep** [comment]
No it’s not. Apparently this feature is part of GitHub’s post-processing of the DOM tree, not part of the GFM syntax spec.
