### ISSUE TITLE
`.markdown-body` with `min-height: 100vh;` may not be expected

### ISSUE THREAD

**Issue by LolipopJ** [sindresorhus/github-markdown-css#115]
I notice there has an update on `.markdown-body` recently:

https://github.com/sindresorhus/github-markdown-css/blob/9ab210a7b09f657d0b79321e8135017d9d64236a/github-markdown.css#L135

I think this may not be what you expect and will cause issues to the interface style.

**Comment by AndersonBY** [comment]
True. Totally messed up my markdown render page.

**Comment by wuyuetian555** [comment]
crazy！

**Comment by earlAchromatic** [comment]
@sindresorhus looks like this didn't get regenerated after sindresorhus/generate-github-markdown-css#40 which should have fixed it.
