### ISSUE TITLE
Markdown language css

### ISSUE THREAD

**Issue by danlevan** [sindresorhus/github-markdown-css#16]
It would be great to have the language css as well for markup:

HTML
```html
<html>...
```

JS
```js
$('#id').show()
```

...

**Comment by sindresorhus** [comment]
Hm?

**Comment by danlevan** [comment]
Markdown code like

\`\`\`html
\<html\>
\`\`\`

will generate the html code

```<code class="lang-html">&lt;html&gt;...</code>```

It would be great to have some language supports like github.

**Comment by sindresorhus** [comment]
It does: https://github.com/sindresorhus/github-markdown-css/blob/bfc9fa896f486570f97eb1d800fa9b9e227d5af9/github-markdown.css#L481-L591

GitHub recently switched their syntax highlighter, so you would need to use the GitHub Markdown API or get your current compiler to update.

**Comment by danlevan** [comment]
Oh you're right, I haven't seen the changes.
Thanks :)
