### ISSUE TITLE
Provide documentation on how to leverage syntax highlighting css

### ISSUE THREAD

**Issue by asadovsky** [sindresorhus/github-markdown-css#18]
The `github-markdown.css` file includes syntax highlighting style rules, e.g.:
https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css#L523

However, it's not clear how to set these classes when generating HTML from Markdown. It would be helpful to provide an explanation of how to do so. (In particular, is there a way to configure [marked](https://github.com/chjj/marked) to set these classes?)

PS: Thanks for writing this great module! I'm using it here: https://github.com/asadovsky/mdviewer

**Comment by simov** [comment]
GitHub uses [pygments](http://pygments.org/) for syntax highlighting, which is a Python library used on their servers. Marked on the other hand is a Javascript parser, used in the browser in your case.

The easiest way would be to use the GitHub's REST API to convert your makrdown files to HTML (just don't forget to supply access token for better quota limits).

**Comment by asadovsky** [comment]
Is there any way to do the highlighting client-side, without any HTTP requests?
E.g. is it possible to configure https://highlightjs.org/ to generate the right class names?

**Comment by simov** [comment]
Yes you can do highlighting in the browser. Take a look at how I do it in my [markdown extension](https://github.com/simov/markdown-viewer) :) I'm using http://prismjs.com/

> E.g. is it possible to configure https://highlightjs.org/ to generate the right class names?

I doubt so (unless you find a JS port of the Pygments highlighter). But you don't need it, because you are using Marked to compile your markdown anyway (btw I'm using it too).

**Comment by asadovsky** [comment]
Thanks @simov! Looks like we had the same idea. :) Maybe I'll try out your extension. (I wrote my own b/c I didn't trust the closed-source ones I'd found.)

Using a client-side JS lib for syntax highlighting (effectively ignoring the syntax highlighting CSS from this module) sounds like a reasonable strategy.

I'll leave this issue as open for @sindresorhus since it'd be nice to mention something in the documentation for this module.

**Comment by simov** [comment]
@asadovsky you can take a look at the code of your extensions. On Linux they are located in `~/.config/google-chrome/Default/Extensions` you can search where they are located in any other OS. But yeah, same reasons here :) also I'm using my extension while editing the readme files for my repositories, so the syntax highlighting is fine.

**Comment by auscompgeek** [comment]
> GitHub uses pygments for syntax highlighting

Actually, that hasn't been true for quite a while now. As of December 2014, GitHub has been using Atom's grammars, via [Linguist](/github/linguist), for syntax highlighting.

**Comment by weblancaster** [comment]
Node wrapper around the `pygments`
https://github.com/rvagg/node-pygmentize-bundled

**Comment by Mottie** [comment]
Just to update this thread...

So in the past year, Pygments is no longer used as GitHub's main syntax highlighter. Although it is still in use on their help, api and Jupyter notebook pages.

GitHub has changed to using PrettyLights. A syntax highlighter which [hasn't been publicly released](https://github.com/github/pages-gem/issues/160#issuecomment-134186272). It is pretty much impossible to find themes for it.

GitHub created a [github-syntax-theme-generator](https://github.com/primer/github-syntax-theme-generator) under their "Primer" organization. To use it, you will need to define a [JSON file with color definitions](https://github.com/primer/github-syntax-theme-generator/blob/master/lib/themes/dark.json). The resulting CSS file can be found in the  [github-syntax-light](https://github.com/primer/github-syntax-light) and [github-syntax-dark](https://github.com/primer/github-syntax-dark) repositories. The generator also creates themes for Ace, Atom and TextMate.

In addition, if you need GitHub Flavored Markdown styles, there is also a separate repository for generating that CSS from SCSS: https://github.com/primer/markdown.
