### ISSUE TITLE
set main in package.json to `github-markdown.css`?

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/github-markdown-css#23]
in case we `@import` it via postcss for example

**Comment by sindresorhus** [comment]
Does PostCSS support `main` for CSS? Can you link to some docs.

**Comment by niftylettuce** [comment]
yeah you just @import the package, it looks in `node_modules` and uses that

https://github.com/postcss/postcss-import

**Comment by niftylettuce** [comment]
thanks man!
