### ISSUE TITLE
License

### ISSUE THREAD

**Issue by controversial** [sindresorhus/github-markdown-css#24]
Shouldn't this technically be considered, at least in part, the property of GitHub? Am I really free to use this under your license terms? I don't think you own it, unless I misunderstand how this created.

**Comment by fidian** [comment]
I asked GitHub directly about this sort of thing.

> I was wondering if the CSS that drives GitHub is under any sort of open source license. I started to use a repository that is the minimal amount of CSS needed to get the GitHub feel. This is based on the official CSS, from what I can tell.
> 
> I link to the CSS file from the package and now my converted markdown looks beautiful. However, they have an issue where a user asks if this is legal. I thought I could ask you directly and maybe GitHub could officially weigh in on the project?
> 
> https://github.com/sindresorhus/github-markdown-css/issues/24

Their response:

> Hey Tyler,
> 
> Thanks for reaching out! Our markdown styles are actually part of our open source Primer toolkit:
> 
> https://github.com/primer/primer-markdown
> 
> I would recommend using that module, which is licensed under the MIT license.
> 
> Hopefully that helps, but let me know if you have any questions!
> 
> Cheers,
> Antonio
> GitHub Support

It appears that it's under MIT and this project is also under MIT so there appears to be no licensing issues.  Seeing how the official source is not usable directly (.scss is great, but not when I link directly to it in my browser), this project still has a reason to exist.

**Comment by Narno** [comment]
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

from https://github.com/primer/primer-markdown/blob/master/LICENSE
