### ISSUE TITLE
github-markdown-css does not play well with codemirror

### ISSUE THREAD

**Issue by prakashsanker** [sindresorhus/github-markdown-css#25]
Including both I get something like this

![screen shot 2016-03-28 at 5 43 16 pm](https://cloud.githubusercontent.com/assets/3914624/14094591/93dc70ea-f50c-11e5-9914-7d2d05941c8a.png)

**Comment by sindresorhus** [comment]
The style is for rendering markdown output. Nothing else. Use Stack a Overflow for support questions.
