### ISSUE TITLE
Question: what is "!>"?

### ISSUE THREAD

**Issue by rstacruz** [sindresorhus/github-markdown-css#27]
Apologies for having to ask here, but this is un-googleable so I had to ask. What does `!>` mean in this script below?

```sh
  "scripts": {
    "make": "github-markdown-css !> github-markdown.css"
  },
```

https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/package.json#L17

**Comment by sindresorhus** [comment]
http://unix.stackexchange.com/a/257141/7678

**Comment by sindresorhus** [comment]
Actually, it's not even needed here.
