### ISSUE TITLE
GitHub markdown styles

### ISSUE THREAD

**Issue by jonrohan** [sindresorhus/github-markdown-css#28]
If you want the actual CSS we use, it's here https://github.com/primer/markdown

**Comment by simov** [comment]
@jonrohan can you add the compiled CSS to the repo?
Or at least provide NPM script for building it.

**Comment by jonrohan** [comment]
> Or at least provide NPM script for building it.

I believe I could do that 👍

**Comment by jonrohan** [comment]
Fixed with https://github.com/primer/markdown/commit/f87a57b189b88b5ee4c7982dfcc90adc8591bbe2

**Comment by simov** [comment]
Thank you!
