### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by jpuck** [sindresorhus/github-markdown-css#44]
Great work, thanks! Just curious if there are any aims to support mobile responsiveness to mirror Github's style? As it is, the font is unreadably small.

Thanks again!

**Comment by sindresorhus** [comment]
Maybe if someone does a good pull request.

**Comment by 3nuc** [comment]
Don't be stupid like me.

If you're making a blog, add this to your `<head>` tag.
```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```
