### ISSUE TITLE
Duplicate Selectors

### ISSUE THREAD

**Issue by Swivelgames** [sindresorhus/github-markdown-css#46]
I noticed when attempting to utilize this that there are quite a few duplicated selectors in here. The one that initially jumped out at me, before I started seeing more, was the `hr` selector. There seems to be three or more different declarations for `hr` styles.

Is it possible this could be deduped?

**Comment by sindresorhus** [comment]
The CSS is generated. It will deduped when you minify the CSS yourself, which most do anyways.
