### ISSUE TITLE
style problem using with hightlight.js

### ISSUE THREAD

**Issue by zzzzbw** [sindresorhus/github-markdown-css#51]
Using markdown.css and  hightlight.js in dark background some style will be covered.
For example,the img below is using github-markdown-css and highlight.js/styles/Darcula.css
![31fec43a-e7b8-42e6-a99d-e50861ea0bb5](https://user-images.githubusercontent.com/10753805/35907900-2db356a8-0c2a-11e8-84d9-c6b5180603f2.jpg)
Actually,it should be
![eaf8d65b-57f8-4601-a3d3-a0f95b6e116e](https://user-images.githubusercontent.com/10753805/35908133-ba3ad682-0c2a-11e8-8f59-7e574dce845b.jpg)
The markdown.css set the `background-color` and cover the style of highlight

**Comment by sindresorhus** [comment]
This CSS is exactly what GitHub uses. If you want something different, like a darker syntax highlight, it's up to you to override the correct styles.
