### ISSUE TITLE
Conflict with highlight.js

### ISSUE THREAD

**Issue by fancyboynet** [sindresorhus/github-markdown-css#52]
Ex, I want to use the highlight style to render the `<pre><code>xxx</code></pre>` area, is there any solution?

**Comment by zzzzbw** [comment]
I have met the same question before,you can see [#51](https://github.com/sindresorhus/github-markdown-css/issues/51)
And I have modify the css style which can compatible the highlight
You can see [demo](https://zzzzbw.github.io/github-markdown-css/)

**Comment by smallst** [comment]
@zzzzbw  great job!
