### ISSUE TITLE
Easy way to apply github-markdown.css to Doxygen generated HTML output?

### ISSUE THREAD

**Issue by pieterconradie** [sindresorhus/github-markdown-css#58]
Hi!

Apologies if this is not the right forum to ask such a beginner question. I have an OS project on GitHub and host the Doxygen generated documentation on my own site. I want my Doxygen generated HTML output to look the same as GitHub Markdown style and found your project. I am able to override the Doxygen CSS by provided a new CSS file.

At the moment I am inspecting each element of github-markdown-css to see how it is formatted and then copy&paste the settings to each of the Doxygen elements (which does not have a one-to-one name mapping).

I was wondering if there was an easier, automated way?

Thanks in advance,
Pieter

**Comment by notlmn** [comment]
I assume that you are looking for a way to apply this CSS to your Doxygen generated HTML _automatically_.

It looks like that Doxygen [allows](http://www.doxygen.nl/manual/customize.html#minor_tweaks_header_css) you to add headers and footers for the content that is generated by it. This CSS (as used by GitHub) is structured in a way that all you need to apply this to your page is to have a container element with the class `markdown-body` and have all the generated HTML inside this container.

For example, in your Doxygen setup you could have header and footer pages in the following way

- `header.html`:
  ``` html
  <!DOCTYPE html>
  <!-- ... --->
  <body>
    <div class="markdown-body>
  ```

- `footer.html`:
  ``` html
    </div>
  </body>
  ```

And then let Doxygen add use the custom CSS file as mentioned in the documentation. And your generated HTML should look like the one below:
``` html
<!DOCTYPE html>
<!-- ... -->
<body>
  <div class="markdown-body">
    <!-- Generated HTML from Doxygen -->
  </div>
</body>
```

I assume this is what you are looking for.

**Comment by pieterconradie** [comment]
Hi @notlm,

Sorry for delayed reply. The class names for Doxygen are different and in the end I had to apply each style manually in a new CSS file. I created a Github project so that other people could use the theme too. It's here:
[https://github.com/piconomix/doxygen-github-markdown-theme](https://github.com/piconomix/doxygen-github-markdown-theme)

Regards,
Pieter
