### ISSUE TITLE
Please include source for demo

### ISSUE THREAD

**Issue by athendrix** [sindresorhus/github-markdown-css#65]
Please include the source markdown file that you use for the demo.
I know that I can "View Source" and get the resulting html,
and you quote part of the source in the demo itself,
but I'd like a raw markdown file that when parsed makes your demo, as that in and of itself would be valuable to me.

Thanks!

**Comment by sindresorhus** [comment]
I don't even remember where I got the demo source from. It's just a bunch of random Markdown rendered using the GitHub Markdown render API. It think it's most Markdown from https://github.com/sindresorhus/generate-github-markdown-css/blob/master/fixture.md
