### ISSUE TITLE
Missing linebreak options

### ISSUE THREAD

**Issue by GustavJaner** [sindresorhus/github-markdown-css#69]
Github markdown allows the use of `<br>` and backslash \ to break a line.
Normal use of <br> tag in the .md file does not result in a line break, but simply renders the literal <br> as part of the text. Same with the backslash \.

So far the only option I've found to produce a linebreak is the double space "  ". 
It might not be the best option for writing/structuring your .md files clearly, since it's not as visible as the other options.

https://gist.github.com/shaunlebron/746476e6e7a4d698b373

**Comment by sindresorhus** [comment]
I don't think this is related to the CSS, but rather the Markdown renderer you're using.

**Comment by GustavJaner** [comment]
True haha. Thanks, I solved it
