### ISSUE TITLE
WebStorm's dark theme not supported (Darcula)

### ISSUE THREAD

**Issue by nifanic** [sindresorhus/github-markdown-css#71]
I'm using "Markdown" plugin by JetBrains that supports custom CSS. The MD renders alright, but completely disrespects dark theme.

WebStorm 2019.3

**Comment by sindresorhus** [comment]
There's no dark mode support as GitHub doesn't support dark mode and this package is just the GitHub readme CSS extracted.

**Comment by sindresorhus** [comment]
You can request dark mode support from GitHub here: support@github.com
