### ISSUE TITLE
github-markdown-css is not AMP compatible

### ISSUE THREAD

**Issue by rbelow** [sindresorhus/github-markdown-css#72]
# Feature request

**First of all thanks for your work at `github-markdown-css`, @sindresorhus.**

## Related Problem

When using `github-markdown-css` with [Next.js AMP](https://nextjs.org/docs/api-reference/next/amp) the [AMP validator throws an error](https://amp.dev/documentation/guides-and-tutorials/learn/validation-workflow/validation_errors/): _"Disallowed !important attribute in CSS"_.

## Solution

`github-markdown-css` is AMP compatible.

## Alternatives

If `github-markdown-css` cannot be AMP compatible then offering a `github-markdown-css-amp` could be an alternative.

**Comment by sindresorhus** [comment]
The CSS is generated. See the readme. And it's just normal CSS. The fact that AMP doesn't allow `!important` is not really a concern for this package. You're of course free to fork and publish an AMP compatible version if you want.
