### ISSUE TITLE
More colors in code ?

### ISSUE THREAD

**Issue by nguxx** [sindresorhus/github-markdown-css#73]
Hi,
I use your css happily with the plugin MarkdownPreview.
It lacks a little bit of colors. print gets no specific color for exemple

```python
a = input("Entrez un premier nombre : ")
b = input("Entrez un deuxième nombre : ")
resultat = f"Le résultat de l'addition de {a} avec {b} est égal à {a + b}"
print(resultat)
```
It would be great get it more colorfull like you see it above
Thanx

**Comment by sindresorhus** [comment]
The syntax highlighting quality is up to your Markdown renderer not this package. Also this CSS is generated from the GitHub CSS.

**Comment by nguxx** [comment]
Do you know why I have more colors  if I open a file directly in Chromium or here in Github (with Chromium too) than if I open it from MardownPreview in the same Chromium (more dull) ?
