### ISSUE TITLE
Error: [UriError]: Scheme contains illegal characters.

### ISSUE THREAD

**Issue by StevenLi-DS** [sindresorhus/github-markdown-css#78]
I'm trying to use the [css file](https://github.com/sindresorhus/github-markdown-css/blob/gh-pages/github-markdown.css) in [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) in vscode but got the following error

```
Error: [UriError]: Scheme contains illegal characters.
```

Am I missing something? Is there any way you can help? Thanks.

**Comment by sindresorhus** [comment]
I would post this over at Markdown PDF instead. This is just a normal CSS file.
