### ISSUE TITLE
第826行 让highlight 的主题背景色失效，有点过分了

### ISSUE THREAD

**Issue by ifxj** [sindresorhus/github-markdown-css#82]
.markdown-body .highlight pre,
.markdown-body pre {
  padding: 16px;
  overflow: auto;
  font-size: 85%;
  line-height: 1.45;
  background-color: #f6f8fa;
  border-radius: 3px;
}

你这第826 行有点过分，让highlight 的主题背景色失效

**Comment by sindresorhus** [comment]
English-only.
