### ISSUE TITLE
Task List style with v5.0.0 differs from that of v4.0.0

### ISSUE THREAD

**Issue by abraj** [sindresorhus/github-markdown-css#92]
Thanks for the great work put into this project.

### Issue Description:
After the release of `v5.0.0`, the style for **task list** in the following situation differs from that of `v4.0.0` (as well as GitHub style).

For example, consider the following markdown (GFM) for a **task list**:
```
- [ ] task list
- [x] checked item
```
The rendered markup for the above markdown with styles from `github-markdown-css v5.0.0` 
is shown as following (screenshot): (_Note the bullet visible in front of each task item_)
<img width="146" alt="Screenshot 2021-11-17 at 7 32 59 PM" src="https://user-images.githubusercontent.com/8170980/142215160-fa4e3729-7123-4393-aca0-73a541499377.png">

However, exactly the same markup with styles from `github-markdown-css v4.0.0` 
is shown as following (screenshot):
<img width="146" alt="Screenshot 2021-11-17 at 7 33 24 PM" src="https://user-images.githubusercontent.com/8170980/142215246-3c1a0bcd-768c-4db5-af84-5bc2af7e5db9.png">

The following is directly rendered using _markdown code_ here (GitHub style):
- [ ] task list
- [x] checked item

So, I believe the bullet visible in front of each task item for `v5.0.0` should not be there.

The output markup (for the above mentioned task list markdown) is given below (for reference):
```
<ul class="contains-task-list">
  <li class="task-list-item"><input class="task-list-item-checkbox" disabled="" type="checkbox"> task list</li>
  <li class="task-list-item"><input class="task-list-item-checkbox" checked="" disabled="" type="checkbox"> checked item</li>
</ul>
```
As expected for the use of this library, a class named `markdown-body` exists in a parent container inside the body.

As as side note, the task list demo on the **demo page** (https://sindresorhus.com/github-markdown-css/#task-list) also shows the bullet item in front of each task item (screenshot):
<img width="249" alt="Screenshot 2021-11-17 at 8 04 36 PM" src="https://user-images.githubusercontent.com/8170980/142220425-85d0d958-d285-4e7d-864f-a90001b8d649.png">

**Comment by hyrious** [comment]
Thanks a lot for reporting, however github's markdown render API seems not returning `<ul class="task-list">` now:
```js
await render(`
- [ ] task list
- [x] checked item
`)
'<ul>\n<li>[ ] task list</li>\n<li>[x] checked item</li>\n</ul>\n'
```
Maybe its another temporary bug in their API. I'll try to fix this style soon.

**Comment by abraj** [comment]
> Maybe its another temporary bug in their API. 

Maybe GitHub's markdown render API by default only renders core GFM spec. As per the spec, task list is an **extension** to the core GFM.
Btw, I was using a markdown-it [plugin](https://www.npmjs.com/package/markdown-it-task-lists) for rendering the task list markdown.

I have updated the css for myself using latest `generate-github-markdown-css@5.0.1`. However, I believe npm package `github-markdown-css` could also be updated to include latest CSS.

Anyways, I believe this issue could now be closed.

**Comment by sindresorhus** [comment]
The style is fixed in https://github.com/sindresorhus/github-markdown-css/releases/tag/v5.1.0
