### ISSUE TITLE
Dark mode doesn't work well with tables

### ISSUE THREAD

**Issue by kunalmodi** [sindresorhus/github-markdown-css#93]
Table cell color isn't set as expected in dark mode:

<img width="1058" alt="Screen Shot 2021-12-02 at 6 20 44 PM" src="https://user-images.githubusercontent.com/791388/144533776-f4f1a024-5508-4075-8c03-62f61e541467.png">

It should likely be forced to `var(--color-fg-default)`

Minimal Example:
```
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/5.0.0/github-markdown.min.css">
<style>
  .markdown-body {
    box-sizing: border-box;
    min-width: 200px;
    max-width: 980px;
    margin: 0 auto;
    padding: 45px;
  }

  @media (max-width: 767px) {
    .markdown-body {
      padding: 15px;
    }
  }
</style>
<article class="markdown-body">
  <h1>Unicorns</h1>
  <p>All the things</p>
  <table>
    <tr>
      <td>Hi</td>
    </tr>
  </table>
</article>
```

**Comment by hyrious** [comment]
Please add `<!DOCTYPE html>`, see https://stackoverflow.com/questions/24258380/font-color-in-a-table-doesnt-inherit-from-parent-div .

**Comment by kunalmodi** [comment]
doh, appreciate the pointer @hyrious!
