### ISSUE TITLE
How to display .md files? Pairs with https://cdn.jsdelivr.net/npm/marked/marked.min.js, but doesn't work well.

### ISSUE THREAD

**Issue by limuyun** [sindresorhus/github-markdown-css#96]

**Comment by limuyun** [comment]
Pairs with `https://cdn.jsdelivr.net/npm/marked/marked.min.js`, but doesn't work well.

**Comment by hyrious** [comment]
Maybe this repo will give you a demo:
https://github.com/hyrious/marked-cli
