### ISSUE TITLE
TODO list marker

### ISSUE THREAD

**Issue by 16pxdesign** [sindresorhus/github-markdown-css#98]
This CSS seems to not remove markers before the checkbox in the to-do list. 

Got:
![Example](https://i.imgur.com/OJQqayI.png)

Expected:
![gh](https://i.imgur.com/qNWh95O.png)

**Comment by hyrious** [comment]
Looks like the `task-list-item` class does not exist in your html. The task list style was fixed in https://github.com/sindresorhus/generate-github-markdown-css/pull/13.

**Comment by 16pxdesign** [comment]
Oh, I see. I was thinking just a simple markdown parser will do the job for me. Thanks for reply
